openapi: 3.1.0
info:
  title: CalorieNinjas Imagetextnutrition Recipe API
  description: Get nutrition and recipe data for 100,000  foods and beverages.
  version: 1.0.0
servers:
- url: https://api.calorieninjas.com/v1
tags:
- name: Recipe
paths:
  /recipe:
    get:
      summary: CalorieNinjas Get recipes
      description: Retrieve a list of recipes matching the search query.
      parameters:
      - name: query
        in: query
        description: A string containing a dish name. Partial match is supported.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful response containing recipe information.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    ingredients:
                      type: string
                    servings:
                      type: string
                    instructions:
                      type: string
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
      security:
      - ApiKeyAuth: []
      tags:
      - Recipe
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
